from __future__ import annotations

import contextlib
import hashlib
import logging
import os
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)


class AudioCache:
    """Disk cache of synthesised speech, keyed by the text and the voice.

    Everything a caller says that we can predict is pre-synthesised into here.
    That is the whole latency strategy: live synthesis costs about a second,
    a cache hit costs a disk read.

    Cached content is generated by us, never user input, so nothing private is
    written to disk.
    """

    def __init__(self, directory: Path, max_bytes: int) -> None:
        self.directory = directory
        self.max_bytes = max_bytes
        try:
            directory.mkdir(parents=True, exist_ok=True)
            self.enabled = True
        except OSError as exc:
            logger.warning("tts cache unusable dir=%s error=%s", directory, exc)
            self.enabled = False

    @staticmethod
    def key(text: str, voice: str) -> str:
        return hashlib.sha256(f"{voice}\x00{text.strip()}".encode()).hexdigest()[:32]

    def path_for(self, text: str, voice: str) -> Path:
        return self.directory / f"{self.key(text, voice)}.mp3"

    def get(self, text: str, voice: str) -> Path | None:
        if not self.enabled:
            return None
        path = self.path_for(text, voice)
        if not path.is_file() or path.stat().st_size == 0:
            return None
        # Touch so that eviction keeps whatever the demo is actually using.
        with contextlib.suppress(OSError):
            os.utime(path, None)
        return path

    def put(self, text: str, voice: str, data: bytes) -> Path | None:
        if not self.enabled or not data:
            return None
        path = self.path_for(text, voice)
        try:
            # Write through a temporary file so a reader never sees a partial mp3.
            with tempfile.NamedTemporaryFile(dir=self.directory, delete=False) as handle:
                handle.write(data)
                temporary = Path(handle.name)
            temporary.replace(path)
        except OSError as exc:
            logger.warning("tts cache write failed error=%s", exc)
            return None
        self._evict_if_needed()
        return path

    def total_bytes(self) -> int:
        if not self.enabled:
            return 0
        try:
            return sum(entry.stat().st_size for entry in self.directory.glob("*.mp3"))
        except OSError:
            return 0

    def entry_count(self) -> int:
        if not self.enabled:
            return 0
        try:
            return sum(1 for _ in self.directory.glob("*.mp3"))
        except OSError:
            return 0

    def _evict_if_needed(self) -> None:
        try:
            entries = sorted(self.directory.glob("*.mp3"), key=lambda p: p.stat().st_mtime)
        except OSError:
            return
        total = sum(entry.stat().st_size for entry in entries)
        while total > self.max_bytes and entries:
            oldest = entries.pop(0)
            try:
                total -= oldest.stat().st_size
                oldest.unlink()
            except OSError:
                continue
